export default function Instructions() {
  
    return (
      <>
        <section className="bg-[#f5f5f5]" >
        <div className=" mx-auto w-10/12  py-14">
            <h2 className="px-4  text-2xl font-bold text-center mb-8 ">Introducing ai generated minecraft</h2>
            <ol>
            <li className="py-4 px-4 flex items-center border-b">
              <div className="flex flex-col">
                <div className="flex align-middle">
                  <span className="serial-number mr-4 flex-shrink-0">1</span><h3 className="font-bold">AI model Oasis</h3>
                </div>
                <div className="pl-12 pr-4">
                  AI-generated Minecraft is generated by the AI model Oasis.
                  Oasis is an AI model that generates a playable, real-time, open-world video game.
                  It&apos;s an AI-driven environment that responds to user inputs in real time.
                </div>
              </div>
            </li>
            <li className="py-4 px-4 flex items-center border-b">
              <div className="flex flex-col">
                <div className="flex align-middle">
                  <span className="serial-number mr-4 flex-shrink-0">2</span><h3 className="font-bold">custom AI-generated Minecraft map</h3>
                </div>
                <div className="pl-12 pr-4">
                  Oasis provides multiple scenes for users to choose from, and also supports custom scenes. Just upload the game screenshots to oasis.
                  <h4 className="py-4 font-bold">Video Tutorial</h4>
                  <iframe class="w-full h-[270px] bg-gray-200 md:h-[550px]" src="https://www.youtube.com/embed/j8XfCGHn3PU?si=DegA-QeE3dX_96n_" title="custom AI-generated Minecraft map" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe>
                </div>
              </div>
            </li>
            </ol>
        </div>
        </section>
      </>
    )
  }